alter table screening_results
  add column if not exists high20_prev numeric,
  add column if not exists high55_prev numeric,
  add column if not exists ma150 numeric,
  add column if not exists low252 numeric,
  add column if not exists close_to_52w_low_ratio numeric,
  add column if not exists base_depth_pct numeric,
  add column if not exists volume_dry_up_ratio numeric,
  add column if not exists trend_template_pass boolean default false,
  add column if not exists donchian20_breakout boolean default false,
  add column if not exists donchian55_breakout boolean default false,
  add column if not exists trend_template_raw numeric,
  add column if not exists setup_quality_raw numeric,
  add column if not exists trend_template_score numeric,
  add column if not exists setup_quality_score numeric,
  add column if not exists buy_zone_low numeric,
  add column if not exists buy_zone_high numeric,
  add column if not exists entry_signal text,
  add column if not exists entry_reason text,
  add column if not exists initial_stop_price numeric,
  add column if not exists sell_watch_price numeric,
  add column if not exists trend_exit_price numeric,
  add column if not exists two_r_price numeric,
  add column if not exists position_size_pct numeric,
  add column if not exists exit_plan text;
