export type Market = "NASDAQ" | "KOSDAQ" | "KOSPI_API";

export type ScreeningRun = {
  id: string;
  market: Market;
  run_date: string;
  market_bullish: boolean;
  market_regime_score?: number | null;
  market_exposure?: number | null;
  selected_count: number;
  scored_count: number;
  candidate_count: number;
  finished_at: string | null;
};

export type ScreeningResult = {
  ticker: string;
  security_name: string | null;
  close: number | null;
  adv20: number | null;
  final_score: number | null;
  rs_rank: number | null;
  trend_score: number | null;
  momentum_score: number | null;
  breakout_score: number | null;
  accumulation_score: number | null;
  vcp_score: number | null;
  atr_pct?: number | null;
  high20_prev?: number | null;
  high55_prev?: number | null;
  ma150?: number | null;
  low252?: number | null;
  close_to_52w_high_ratio?: number | null;
  close_to_52w_low_ratio?: number | null;
  close_to_ma50_ratio?: number | null;
  base_depth_pct?: number | null;
  volume_dry_up_ratio?: number | null;
  trend_template_pass?: boolean | null;
  donchian20_breakout?: boolean | null;
  donchian55_breakout?: boolean | null;
  trend_template_score?: number | null;
  setup_quality_score?: number | null;
  entry_pivot?: number | null;
  buy_zone_low?: number | null;
  buy_zone_high?: number | null;
  entry_extension_pct?: number | null;
  breakout_entry?: boolean | null;
  pullback_entry?: boolean | null;
  entry_setup?: string | null;
  entry_signal?: string | null;
  entry_reason?: string | null;
  entry_trigger: boolean | null;
  stop_price: number | null;
  stop_basis?: string | null;
  initial_stop_price?: number | null;
  sell_watch_price?: number | null;
  trend_exit_price?: number | null;
  two_r_price?: number | null;
  position_size_pct?: number | null;
  exit_plan?: string | null;
  risk_to_stop: number | null;
  is_candidate: boolean;
};

export type DashboardData = {
  market: Market;
  run: ScreeningRun | null;
  candidates: ScreeningResult[];
  scored: ScreeningResult[];
  usingSampleData: boolean;
};
